const portfolioItems = [
    {
        "portfolioId": 1,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " az.polychallenge.org",
        "portfolioImage": "/polyup.png",
    },
    {
        "portfolioId": 2,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " tehsilucun.edu.az",
        "portfolioImage": "/tehsilucun.edu.az.png",
    },
    {
        "portfolioId": 3,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " d-tech.az",
        "portfolioImage": "/d-tech.az.png",
    },
    {
        "portfolioId": 4,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " tkta.edu.az",
        "portfolioImage": "/tkta.edu.az.png",
    },
    {
        "portfolioId": 5,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " edu.gov.az - Accessibility",
        "portfolioImage": "",
    },
    {
        "portfolioId": 6,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " globalinnovationcatalyst.com",
        "portfolioImage": "/gic.com.png",
    },
    {
        "portfolioId": 7,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " enginet.az",
        "portfolioImage": "/enginet.az.png",
    },
    {
        "portfolioId": 8,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " test.gov.az",
        "portfolioImage": "",
    },
    {
        "portfolioId": 9,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " tmis.edu.az",
        "portfolioImage": "/ali.tmis.edu.az.png",
    },
    {
        "portfolioId": 10,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " sorgu.edu.az",
        "portfolioImage": "/sorgu.edu.az.png",
    },
    {
        "portfolioId": 11,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " polyup.az",
        "portfolioImage": "/polyup.az.png",
    },
    {
        "portfolioId": 12,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " e-diplom.edu.gov.az",
        "portfolioImage": "",
    },
    {
        "portfolioId": 13,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " scanex.az",
        "portfolioImage": "",
    },
    {
        "portfolioId": 14,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " virtual-mekteb.edu.az",
        "portfolioImage": "",
    },
    {
        "portfolioId": 15,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " waxberrycapital.com",
        "portfolioImage": "",
    },
    {
        "portfolioId": 16,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": " manikur.az",
        "portfolioImage": "",
    },


    {
        "portfolioId": 1,
        "portfolioCategory": "film",
        "portfolioColor": "color_1",
        "portfolioName": "portfolio name 1",
    },
    {
        "portfolioId": 2,
        "portfolioCategory": "photos",
        "portfolioColor": "color_1",
        "portfolioName": "portfolio name 2",
    },
    {
        "portfolioId": 3,
        "portfolioCategory": "frontend",
        "portfolioColor": "color_1",
        "portfolioName": "portfolio name 3",
    },
];

export default portfolioItems;

